### ISSUE TITLE
Please Adding the Indonesian Language...

### ISSUE THREAD

**Issue by AnomSanjaya** [metonator/GameLauncher_NFSW-translations#17]
Hi, i am NFSW player....
I'm creating the Translated SBRW Launcher to Indonesian language, because the previous SBRW version or NFSW official launchers couldn't support Indonesian language, so this is my initation fo facilitate the NFSW players in Indonesia.

[Indonesian.zip](https://github.com/metonator/GameLauncher_NFSW-translations/files/1943668/Indonesian.zip)

I'm hope do you like this... 
Thank you.

**Comment by metonator** [comment]
You could just create new file here and put its content. Btw, gonna do pull request asap, thanks for help on translation
