### ISSUE TITLE
Reverse name changes of German translations

### ISSUE THREAD

**Issue by netswap** [metonator/GameLauncher_NFSW-translations#3]
The filenames for the different German translations were fine - swapping the names was done wrongfully.
Sie -> Formal
Du -> Informal

tl;dr: filenames were fine before the last namechange.

...coming from a native speaker.

If this someone proves me wrong, then I might have skipped too many German classes to pass the finals. :v

**Comment by metonator** [comment]
Changed, thanks for correcting me
